:-dynamic rhyme/2.
assert(rhyme(call, fall)).
assert(rhyme(race, pace)).
assert(rhyme(duck, muck)).
assert(rhyme(paani, manmaani)).
assert(rhyme(high, lie)).
assert(rhyme(nice, vice)).
assert(rhyme(vice, dice)).
assert(rhyme(mice, dice)).
assert(rhyme(bus, pus)).
assert(rhyme(mice, rice)).
assert(rhyme(rice, lice)).
assert(rhyme(thyme, lime)).